### PR TITLE
Add lcd-tools

### PR DESCRIPTION
**Pull request by LecrisUT**
Depends on [AsteroidOS/lcd-tools#1](https://github.com/AsteroidOS/lcd-tools/pull/1)

Previous PR is at [meta-cafish-hybris#5](https://github.com/AsteroidOS/meta-catfish-hybris/pull/5)

### CODE REVIEW

**Comment by LecrisUT** [comment]
The fix is ready for review. The source is at [LecrisUT/lcd-tools](https://github.com/LecrisUT/lcd-tools), but it should be moved to the organization. @FlorentRevest you mentioned making the repository, but I haven't been invited as collaborator.

For now let's go with the non-qt version, but if anyone can help port it, I'm all for it.

@MagneFire can you also upload `nanohub.full.catshark.19061201.bin` to the dropbox?

**Comment by MagneFire** [comment]
> The fix is ready for review. The source is at [LecrisUT/lcd-tools](https://github.com/LecrisUT/lcd-tools), but it should be moved to the organization. @FlorentRevest you mentioned making the repository, but I haven't been invited as collaborator.
> 

The repository is located here: https://github.com/AsteroidOS/lcd-tools
I think you can rebase your work on top of that and create a PR so that one of the maintainers can review the code.

> For now let's go with the non-qt version, but if anyone can help port it, I'm all for it.
> 
> @MagneFire can you also upload `nanohub.full.catshark.19061201.bin` to the dropbox?

Sure, where do you want it to be located on Dropbox?

**Comment by LecrisUT** [comment]
> Sure, where do you want it to be located on Dropbox?

Along with the `catfish-ext` version (`nanohub.full.catshark.19090317.bin`).

https://github.com/AsteroidOS/lcd-tools is private so I can't get the initial commits to rebase or make a PR

**Comment by MagneFire** [comment]
> > Sure, where do you want it to be located on Dropbox?
> 
> Along with the `catfish-ext` version (`nanohub.full.catshark.19090317.bin`).
> 

What `catfish-ext` version? Or do you mean a new tarball that uses the `nanohub.full.catshark.19090317.bin` firmware?
(Replace this line with one specific for `catfish-ext`: https://github.com/AsteroidOS/meta-smartwatch/blob/master/meta-catfish/recipes-android/android/android_catfish-n.bb#L7)

So to create a separate watch in the build system similar to what we did for `ray` and `firefish`.

> https://github.com/AsteroidOS/lcd-tools is private so I can't get the initial commits to rebase or make a PR

I've changed visibility of the repository. It should now be public. Thanks for pointing out :smile:

**Comment by LecrisUT** [comment]
Yes, I was referring to the one in https://dl.dropboxusercontent.com/s/q017d5vd1diiww1/system-catfish-pie-preview.tar.gz. If I remember correctly this one is for TicWatch 2020 containing `nanohub.full.catshark.19090317.bin`, but from previous testing, we've found that simply containing both copies work for both watches, so for now we don't need to separate the watches yet. But anyway that's an issue for another PR.

**Comment by FlorentRevest** [comment]
Thank you @LecrisUT ! :)

**Pull request merged**
