### PR TITLE
Update to mickledore

### PR DESCRIPTION
**Pull request by beroset**
This is part of the fix for https://github.com/AsteroidOS/asteroid/issues/245 to update from kirkstone to mickledore.

### CODE REVIEW

**Review by eLtMosen — COMMENTED** [review]
Appreciate your thorough commit messages!
Keep it up, i am actually reading and trying to follow/learn ;)

**Comment by beroset** [comment]
Rebased on the current master.

**Comment by beroset** [comment]
Thanks very much to @MagneFire for the qtwayland patch that I had somehow missed originally.

**Comment by MagneFire** [comment]
This also needs https://github.com/MagneFire/meta-asteroid/commit/bc65ae647e3494f50fd58016e1c8bf006b33fc74 to fix compilation of some of the older kernels (`sturgeon` for example).

Additionally, it appears that this also fails to compile on `beluga`. I can attach a trace for that one later. But it appears to be related to the external kernel modules.

**Review by FlorentRevest — APPROVED** [review]

**Review by FlorentRevest — APPROVED** [review]

**Comment by MagneFire** [comment]
Audio doesn't work in this one. Three more recipes need changes: `pulseaudio-modules-keepalive`, `pulseaudio-modules-droid`, `pulseaudio-modules-nemo`.
See the changes here: https://github.com/MagneFire/meta-asteroid/commits/update-to-mickledore

**Comment by MagneFire** [comment]
I needed to apply some changes for it to compile and work on `sturgeon`: https://github.com/AsteroidOS/meta-asteroid/compare/7ffbee617ce685aa303bd96f51c62500df8998aa...MagneFire:meta-asteroid:update-to-mickledore
Only the `libhybris` related commit is really needed for `sturgeon`, the other two are needed to fix build issues (also fixing https://github.com/AsteroidOS/asteroid/issues/272).

**Comment by beroset** [comment]
Thanks for this -- I was just working on something similar!  To my knowledge, this addresses the last remaining issues with moving to `mickledore`.

**Review by FlorentRevest — APPROVED** [review]
Thanks for driving this migration. FWIW, this looks fine by me and feel free to merge when appropriate

**Pull request merged**
